//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCityParkServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Codigo
    {
        public int CodigoId { get; set; }
        public string Codigo1 { get; set; }
        public int UsuarioId { get; set; }
        public int DispositivoId { get; set; }
        public bool Usado { get; set; }
    
        public virtual Dispositivo Dispositivo { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
