//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCityParkServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dispositivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dispositivo()
        {
            this.Codigo = new HashSet<Codigo>();
        }
    
        public int DispositivoId { get; set; }
        public Nullable<int> SOId { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public string UniqueId { get; set; }
        public Nullable<int> EmpresaId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Codigo> Codigo { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual SO SO { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
