//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCityParkServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MensajeContacto
    {
        public int idMensajeContacto { get; set; }
        public bool isUsuario { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public Nullable<int> VendedorId { get; set; }
        public string Mensaje { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Vendedor Vendedor { get; set; }
    }
}
