//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCityParkServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Multa
    {
        public int MultaId { get; set; }
        public Nullable<int> SalarioBasicoId { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public DateTime Fecha { get; set; }
        public Nullable<int> AgenteId { get; set; }
        public Nullable<double> Longitud { get; set; }
        public Nullable<double> latitud { get; set; }
        public string Placa { get; set; }
        public string Plaza { get; set; }
        public string Foto { get; set; }
        public Nullable<int> EmpresaId { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> TipoMultaId { get; set; }
    
        public virtual Agente Agente { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual SalarioBasico SalarioBasico { get; set; }
        public virtual TipoMultas TipoMultas { get; set; }
    }
}
