//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCityParkServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parqueo
    {
        public int ParqueoId { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public DateTime FechaInicio { get; set; }
        public DateTime FechaFin { get; set; }
        public Nullable<double> Latitud { get; set; }
        public Nullable<double> Longitud { get; set; }
        public Nullable<int> TarjetaCreditoId { get; set; }
        public Nullable<int> CarroId { get; set; }
        public Nullable<int> PlazaId { get; set; }
        public Nullable<int> EmpresaId { get; set; }
    
        public virtual Carro Carro { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual TarjetaCredito TarjetaCredito { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
