//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCityParkServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plaza
    {
        public int PlazaId { get; set; }
        public string Nombre { get; set; }
        public string Barrio { get; set; }
        public string Direccion { get; set; }
        public Nullable<bool> Ocupado { get; set; }
        public Nullable<double> Longitud { get; set; }
        public Nullable<double> Latitud { get; set; }
        public Nullable<int> EmpresaId { get; set; }
    
        public virtual Empresa Empresa { get; set; }
    }
}
