
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AppCityParkServices.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class PuntoSector
{

    public int PuntoSectorId { get; set; }

    public Nullable<double> Latitud { get; set; }

    public Nullable<double> Longitud { get; set; }

    public Nullable<int> SectorId { get; set; }

    public virtual Sector Sector { get; set; }

}

}
