//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCityParkServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarjetaPrepago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TarjetaPrepago()
        {
            this.UsuarioTarjetaPrepago = new HashSet<UsuarioTarjetaPrepago>();
        }
    
        public int TarjetaPrepagoId { get; set; }
        public string Numero { get; set; }
        public decimal Saldo { get; set; }
        public System.DateTime FechaVence { get; set; }
        public bool Activa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioTarjetaPrepago> UsuarioTarjetaPrepago { get; set; }
    }
}
