//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCityParkServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioTarjetaPrepago
    {
        public int UsuarioTarjetaPrepagoId { get; set; }
        public int UsuarioId { get; set; }
        public int TarjetaPrepagoId { get; set; }
    
        public virtual TarjetaPrepago TarjetaPrepago { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
